
		<!-- class=section marks the sections reflecting the directory structure
			 class=toc means these parts only show up in the big toc page but are hidden in the left hand navigation
			 class=toc is applied to so called anchors, which aid navigation within long pages -->
		
		
		<!-- index -->
		<ul class="section toc">
			<li class="secindex"><a href="/index.html">Documentation Home</a></li>
			<ul class="toc">
					<li><a href="/index.html#o1011">Downloads</a></li>
					<li><a href="/index.html#o1015">Support</a></li>
					<li><a href="/index.html#o1013">License</a></li>
			</ul>
		</ul>

		<!-- overview -->
		<ul class="section">
			<li class="secindex"><a href="/overview/index.html"><span class="toc">Mulgara </span>Overview</a></li>
<!--#if expr="${DOCUMENT_NAME} = /toc/" --> 	
		<!--#include virtual='/overview/includeTOC.inc' -->
	<!--#elif expr="${DOCUMENT_URI} = /overview/" -->
		<!--#include virtual='/overview/includeTOC.inc' -->
	<!--#endif -->	
		</ul>
		
		
		<!-- tutorial -->
		<ul class="section">
			<li class="secindex"><a href="/tutorial/index.html"><span class="toc">Mulgara </span>Tutorial</a></li>
<!--#if expr="${DOCUMENT_NAME} = /toc/" --> 	
		<!--#include virtual='/tutorial/includeTOC.inc' -->
	<!--#elif expr="${DOCUMENT_URI} = /tutorial/" -->
		<!--#include virtual='/tutorial/includeTOC.inc' -->
	<!--#endif -->	
		</ul>
		
		<div class="navtocseperator"></div>
	
		<!-- system -->
		<ul class="section">		
			<li class="secindex"><a href="/system/index.html">System Architecture</a></li>
<!--#if expr="${DOCUMENT_NAME} = /toc/" --> 	
		<!--#include virtual='/system/includeTOC.inc' -->
	<!--#elif expr="${DOCUMENT_URI} = /system/" -->
		<!--#include virtual='/system/includeTOC.inc' -->
	<!--#endif --> 
		</ul>
	
	
		<!-- resolvers -->
		<ul class="section">	
			<li class="secindex"><a href="/resolvers/index.html">Resolvers</a></li>
<!--#if expr="${DOCUMENT_NAME} = /toc/" --> 	
		<!--#include virtual='/resolvers/includeTOC.inc' -->
	<!--#elif expr="${DOCUMENT_URI} = /resolvers/" -->
		<!--#include virtual='/resolvers/includeTOC.inc' -->
	<!--#endif --> 
		</ul>
	
	
		<!-- descriptors -->
		<ul class="section">			
			<li class="secindex"><a href="/descriptors/index.html">Descriptors</a></li>
<!--#if expr="${DOCUMENT_NAME} = /toc/" --> 	
		<!--#include virtual='/descriptors/includeTOC.inc' -->
	<!--#elif expr="${DOCUMENT_URI} = /descriptors/" -->
		<!--#include virtual='/descriptors/includeTOC.inc' -->
	<!--#endif --> 
		</ul>
	
	
		<!-- integration -->
		<ul class="section">	
			<li class="secindex"><a href="/integration/index.html">Integration Tutorials</a></li>
<!--#if expr="${DOCUMENT_NAME} = /toc/" --> 	
		<!--#include virtual='/integration/includeTOC.inc' -->
	<!--#elif expr="${DOCUMENT_URI} = /integration/" -->
		<!--#include virtual='/integration/includeTOC.inc' -->
	<!--#endif --> 
		</ul>
		
		<div class="navtocseperator"></div>

		<!-- itqlcommands -->
		<ul class="section">	
			<li class="secindex"><a href="/itqlcommands/index.html">iTQL Commands</a></li>
<!--#if expr="${DOCUMENT_NAME} = /toc/" --> 	
		<!--#include virtual='/itqlcommands/includeTOC.inc' -->
	<!--#elif expr="${DOCUMENT_URI} = /itqlcommands/" -->
		<!--#include virtual='/itqlcommands/includeTOC.inc' -->
	<!--#endif --> 
		</ul>
	
	
		<!-- itqloperations -->
		<ul class="section">	
			<li class="secindex"><a href="/itqloperations/index.html">Advanced iTQL<span class="toc"> Operations</span></a></li>
<!--#if expr="${DOCUMENT_NAME} = /toc/" --> 	
		<!--#include virtual='/itqloperations/includeTOC.inc' -->
	<!--#elif expr="${DOCUMENT_URI} = /itqloperations/" -->
		<!--#include virtual='/itqloperations/includeTOC.inc' -->
	<!--#endif --> 
		</ul>
	
	
		<!-- inferencing -->
		<ul class="section">	
			<li class="secindex"><a href="/inferencing/index.html">Inferencing</a></li>
<!--#if expr="${DOCUMENT_NAME} = /toc/" --> 	
		<!--#include virtual='/inferencing/includeTOC.inc' -->
	<!--#elif expr="${DOCUMENT_URI} = /inferencing/" -->
		<!--#include virtual='/inferencing/includeTOC.inc' -->
	<!--#endif --> 
		</ul>
		
		<div class="navtocseperator"></div>
		
		<!-- therest -->
		<ul class="section">	
			<li class="secindex2"><a href="/toc.html">Table of Contents</a></li>
			<li class="secindex2"><a href="/backofbook.html">Index</a></li>
		</ul>
		<ul class="section">
			<li><div id="searchcontrol"/></li>
		</ul>