
		</div>
		<!-- end of main content -->


		<div id="footer">
			<div id="copyright">
				<a href="http://www.opensource.org/docs/definition.php" title="Open Source Initiative"><img style="border:0;width:55px;height:48px;" src="/img-layout/opensource-55x48.png" alt="Open Source logo" /></a>
				<p>&copy; 2001-2004 Tucana Technologies, Inc. Some rights reserved.</p>    
				<p>&copy; 2006 The Mulgara Project. Some rights reserved.<br />
					Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or any later version published by the Free Software Foundation; with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A copy of the license is included in the section entitled &quot;<a href="/legal/fdl.txt">GNU Free Documentation License</a>&quot;.
				</p>
				<p>Modification Authors:  Paul Gearon, David Wood.  Principle Authors: Tom Adams, Grant Noble.  The publisher of this version is <a href="http://mulgara.org">The Mulgara Project</a>. <a href="/overview/history.html">Document history</a>.</p>
			</div>
			<div id="lastmodified">
				 This file was last modified on 
				<!--#config timefmt="%A, %B %e. %Y - %T %Z" -->
				<!--#echo var="LAST_MODIFIED" -->.
			</div>
		</div>
	</div>
	<!-- end of right column -->
	
	<div id="sfx" title="Switch specialFX ON unless you have slow hardware. It provides a fixed header while you scroll, leaving the navigation always in reach."></div>
	
</body>
</html>