
    <meta name="description" content="Mulgara semantic store is a scalable RDF database written entirely in Java. It is an Open Source fork of Kowari metastore." />
	<meta name="copyright" content="Copyright &copy; 2006, Mulgara Project" />
	
	<meta name="DC.Title" content="mulgara semantic store" />
    <meta name="DC.Subject" content="mulgara project, metadata, metastore, metadatabase, datastore, database, scaleable, scalable, transaction, java, open source, rdf, resource description framework" />
    <meta name="DC.Description" content="Mulgara semantic store is a scalable RDF database written entirely in Java. It is an Open Source fork of Kowari metastore." />
    <meta name="DC.Creator" content="Tom Adams" />
    <meta name="DC.Contributor" content="Paul Gearon" />
    <meta name="DC.Contributor" content="David Wood" />
    <meta name="DC.Date.Created" scheme="iso8601" content="2003-09-22" />
    <meta name="DC.Modified" scheme="iso8601" content="2006-10-01" />
    <meta name="DC.Language" scheme="rfc1766" content="en" />
    <meta name="DC.Type" scheme="http://memory.loc.gov/ammem/award99/icuhtml/dcguide.html" content="Text.Homepage.Organizational" />
    <meta name="DC.Identifier" scheme="URI" content="http://mulgara.org/" />
    <meta name="DC.Rights" scheme="URI" content="http://opensource.org/licenses/osl-3.0.php" />
    
    <script type="text/javascript" src="/script/bodyswitcher.js"></script>
    <style type="text/css">@import url(/style/style.css);</style>
    <!--[if IE]><style type="text/css">@import url(/style/styleIE6.css);</style><![endif]-->

</head>

 <body>
	<div id="logo"><a href="/index.html"><img src="/img-layout/spacer.gif" width="800" height="56" alt="mulgara semantic store (big logo)" /></a></div>
    <div id="backTop1"></div>
    <div id="backTop2"></div>
      
    <div id="siteNaviTopBack"></div>
    <div id="siteNaviTop"><a href="/index.html">Docs Home</a></div>
    <div id="leftCol">
    	<div id="siteNavi">	
<!-- SITE NAVIGATION STARTS HERE -->
		<!--#include virtual='/includeTOC.inc' -->
<!-- SITE NAVIGATION ENDS HERE -->      
		</div>
    </div>

		
