/* Generated By:JavaCC: Do not edit this line. RlogParserConstants.java */
package org.mulgara.krule.rlog;

public interface RlogParserConstants {

  int EOF = 0;
  int COMMENT = 7;
  int PREFIX = 8;
  int LOWER_CASE_LETTER = 9;
  int UPPER_CASE_LETTER = 10;
  int DIGIT = 11;
  int J_LETTER_DIGIT = 12;
  int IMPLIED_BY = 13;
  int INVERT = 14;
  int NEGATE = 15;
  int DOT = 16;
  int COMMA = 17;
  int LPAR = 18;
  int RPAR = 19;
  int STRING_LITERAL = 20;
  int URI = 21;
  int IDENTIFIER = 22;
  int VARIABLE = 23;
  int TYPE = 24;
  int INTEGER_LITERAL = 25;
  int DOMAIN = 26;

  int DEFAULT = 0;
  int IN_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\" \"",
    "\"--\"",
    "<COMMENT>",
    "\"@prefix\"",
    "<LOWER_CASE_LETTER>",
    "<UPPER_CASE_LETTER>",
    "<DIGIT>",
    "<J_LETTER_DIGIT>",
    "\":-\"",
    "\"~\"",
    "\"-\"",
    "\".\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "<STRING_LITERAL>",
    "<URI>",
    "<IDENTIFIER>",
    "<VARIABLE>",
    "<TYPE>",
    "<INTEGER_LITERAL>",
    "<DOMAIN>",
  };

}
