				<ul>
						<li><a href="/itqloperations/views.html">Views</a></li>
						<ul class="toc">
								<li><a href="/itqloperations/views.html#o3012">Creating Views</a></li>
								<li><a href="/itqloperations/views.html#o3013">Querying View Definitions</a></li>
								<li><a href="/itqloperations/views.html#o256">Limitations of Views</a></li>
						</ul>
						<li><a href="/itqloperations/fulltextmodels.html">Full-Text Models</a></li>
						<ul class="toc">
								<li><a href="/itqloperations/fulltextmodels.html#o258">Creating Full-Text Models</a></li>
								<li><a href="/itqloperations/fulltextmodels.html#o259">Modifying Full-Text Models</a></li>
								<li><a href="/itqloperations/fulltextmodels.html#o260">Querying Full-Text Models</a></li>
								<li><a href="/itqloperations/fulltextmodels.html#o261">Limitations of Full-Text Models</a></li>
						</ul>
						<li><a href="/itqloperations/datatypingmodels.html">Datatyping Models</a></li>
						<ul class="toc">
								<li><a href="/itqloperations/datatypingmodels.html#o263">Creating Datatyping Models</a></li>
								<li><a href="/itqloperations/datatypingmodels.html#o264">Loading Datatyping Models</a></li>
								<li><a href="/itqloperations/datatypingmodels.html#o265">Querying Datatyping Models</a></li>
								<li><a href="/itqloperations/datatypingmodels.html#o266">Limitations of Datatyping Models</a></li>
						</ul>
						<li><a href="/itqloperations/nodetyping.html">Nodetyping Models</a></li>
						<ul class="toc">
								<li><a href="/itqloperations/nodetyping.html#o2780">Creating Nodetyping Models</a></li>
								<li><a href="/itqloperations/nodetyping.html#o2781">Querying Nodetyping Models</a></li>
						</ul>
						<li><a href="/itqloperations/filesysmodel.html">Filesystem Models</a></li>
						<ul class="toc">
								<li><a href="/itqloperations/filesysmodel.html#o3202">Creating Filesystem Models</a></li>
								<li><a href="/itqloperations/filesysmodel.html#o3204">Updating Filesystem Models</a></li>
								<li><a href="/itqloperations/filesysmodel.html#o3203">Querying Filesystem Models</a></li>
						</ul>
				</ul>
