				<ul>
						<li><a href="/descriptors/descwhat.html">What are Descriptors?</a></li>
						<li><a href="/descriptors/descadvantages.html">Advantages and Disadvantages of Descriptors</a></li>
						<li><a href="/descriptors/nsdesc.html">Namespaces and Descriptors</a></li>
						<li><a href="/descriptors/querytag.html">The &lt;query&gt; Tag</a></li>
						<li><a href="/descriptors/descriptortag.html">The &lt;descriptor&gt; Tag</a></li>
						<li><a href="/descriptors/reserved.html">Reserved Parameters</a></li>
						<li><a href="/descriptors/descriptorsfaq.html">Descriptors FAQ</a></li>
						<li><a href="/descriptors/mistakes.html">Common Mistakes</a></li>
						<li><a href="/descriptors/descriptorex.html">Descriptor Examples</a></li>
						<ul>
								<li><a href="/descriptors/descriptorhw.html">Hello World Descriptor</a></li>
								<li><a href="/descriptors/descriptorlist.html">List Models Descriptor</a></li>
								<li><a href="/descriptors/descriptorvcard.html">VCard Descriptors</a></li>
						</ul>
				</ul>
