				<ul>
						<li><a href="/system/jsptaglib.html">JavaServer Pages Tag Library</a></li>
						<ul class="toc">
								<li><a href="/system/jsptaglib.html#o486">Software Requirements</a></li>
								<li><a href="/system/jsptaglib.html#o487">Configuring your Web Application</a></li>
								<li><a href="/system/jsptaglib.html#o493">answer</a></li>
								<li><a href="/system/jsptaglib.html#o492">execute</a></li>
								<li><a href="/system/jsptaglib.html#o488">init</a></li>
								<li><a href="/system/jsptaglib.html#o491">query</a></li>
								<li><a href="/system/jsptaglib.html#o489">render</a></li>
								<li><a href="/system/jsptaglib.html#o490">statement</a></li>
						</ul>
						<li><a href="/system/itqlshell.html">iTQL Shell</a></li>
						<li><a href="/system/soap.html">Simple Object Access Protocol (SOAP)</a></li>
						<li><a href="/system/itqlbean.html">iTQL Bean</a></li>
						<li><a href="/system/driver.html">Mulgara Driver</a></li>
						<li><a href="/system/jrdf.html">Java RDF (JRDF)</a></li>
						<ul>
								<li><a href="/system/jrdfapis.html">JRDF APIs</a></li>
								<li><a href="/system/jrdfgraphs.html">JRDF Graphs</a></li>
								<ul class="toc">
										<li><a href="/system/jrdfgraphs.html#o2470">Triples</a></li>
										<li><a href="/system/jrdfgraphs.html#o2471">SubjectNodes</a></li>
										<li><a href="/system/jrdfgraphs.html#o2472">PredicateNodes</a></li>
										<li><a href="/system/jrdfgraphs.html#o2473">ObjectNodes</a></li>
										<li><a href="/system/jrdfgraphs.html#o2474">URIReferences</a></li>
										<li><a href="/system/jrdfgraphs.html#o2475">BlankNodes</a></li>
										<li><a href="/system/jrdfgraphs.html#o2476">Literals</a></li>
										<li><a href="/system/jrdfgraphs.html#o2478">GraphElementFactory</a></li>
										<li><a href="/system/jrdfgraphs.html#o2479">Querying a JRDF Graph</a></li>
								</ul>
								<li><a href="/system/jrdftks.html">TKS Client Support</a></li>
								<li><a href="/system/jrdfmemory.html">JRDF Memory Implementation</a></li>
								<li><a href="/system/jrdfconcol.html">Containers and Collections</a></li>
								<ul class="toc">
										<li><a href="/system/jrdfconcol.html#o2527">Triple Factory</a></li>
								</ul>
								<li><a href="/system/jrdfvisitor.html">Built-in Visitor Pattern</a></li>
								<ul class="toc">
										<li><a href="/system/jrdfvisitor.html#o2529">TypedNodeVisitable</a></li>
										<li><a href="/system/jrdfvisitor.html#o2530">TypedNodeVisitor</a></li>
								</ul>
								<li><a href="/system/jrdfexamples.html">Examples</a></li>
								<ul class="toc">
										<li><a href="/system/jrdfexamples.html#o2514">JRDF Graph (Memory)</a></li>
										<ul>
												<li><a href="/system/jrdfexamples.html#o2515">Create a JRDF Graph and add Triples</a></li>
												<li><a href="/system/jrdfexamples.html#o2516">Query the JRDF Graph</a></li>
												<li><a href="/system/jrdfexamples.html#o2517">Remove a Triple from the JRDF Graph</a></li>
										</ul>	
										<li><a href="/system/jrdfexamples.html#o2518">Mulgara Backed JRDF Graph (Client)</a></li>
										<ul>	
												<li><a href="/system/jrdfexamples.html#o2519">Create a Mulgara Session</a></li>
												<li><a href="/system/jrdfexamples.html#o2520">Create a Mulgara Backed JRDF Graph</a></li>
										</ul>
										<li><a href="/system/jrdfexamples.html#o2521">Display iTQL Results as an JRDF Graph</a></li>
										<ul>
												<li><a href="/system/jrdfexamples.html#o2523">Execute an iTQL Query</a></li>
												<li><a href="/system/jrdfexamples.html#o2524">Create a JRDF Graph from the Results</a></li>
										</ul>
								</ul>
						</ul>
				</ul>
