#!/bin/sh
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the Kowari Metadata Store.
#
# The Initial Developer of the Original Code is Plugged In Software Pty
# Ltd (http://www.pisoftware.com, mailto:info@pisoftware.com). Portions
# created by Plugged In Software Pty Ltd are Copyright (C) 2001,2002
# Plugged In Software Pty Ltd. All Rights Reserved.
#
# Contributor(s): N/A.
#
# [NOTE: The text of this Exhibit A may differ slightly from the text
# of the notices in the Source Code files of the Original Code. You
# should use the text of this Exhibit A rather than the text found in the
# Original Code Source Code for Your Modifications.]

#
# Shell script for starting and stopping embedded KOWARI server fo use in
# automated testing.
#
# $Id: kowari-2serv,v 1.5 2004/12/22 05:02:07 newmana Exp $
#


# check JAVA_HOME environment variable
if [ "$JAVA_HOME" = "" ] ; then
  echo "Please set a JAVA_HOME environment variable" >&2
  echo -e "For example:\n" >&2
  echo -e "  $ export JAVA_HOME=/usr/local/java\n" >&2
  exit 1
fi

# check KOWARI_DIR environment variable
if [ "$KOWARI_DIR" = "" ] ; then
  echo "Please set a KOWARI_DIR environment variable pointing to the location of the" >&2
  echo -e "KOWARI executable JAR\n" >&2
  echo -e "For example:\n" >&2
  echo -e "  $ export KOWARI_DIR=/home/jsmith/kowari/dbms/dist\n" >&2
  exit 1
fi

# set variables
SLEEP_TIME=5
OLD_DIR=$PWD
RMIPID=$KOWARI_DIR/rmiregistry.pid
KOWARI1PID=$KOWARI_DIR/kowari1.pid
KOWARI2PID=$KOWARI_DIR/kowari2.pid

# perform the requested action
case "$1" in
    start)
        cd $KOWARI_DIR
        /sbin/start-stop-daemon \
            --start \
            --pidfile $RMIPID \
            --make-pidfile \
            --background \
            --exec $JAVA_HOME/bin/rmiregistry
        /sbin/start-stop-daemon \
            --start \
            --pidfile $KOWARI1PID \
            --make-pidfile  \
            --exec $JAVA_HOME/bin/java -- -jar $KOWARI_DIR/kowari-1.0.jar \
            >> kowari1-output 2>> kowari1-output &
        /sbin/start-stop-daemon \
            --start \
            --pidfile $KOWARI2PID \
            --make-pidfile  \
            --exec $JAVA_HOME/bin/java -- -jar $KOWARI_DIR/kowari-1.0.jar -l file://$KOWARI_DIR/../conf/log4j-kowari-2servers.xml -t file://$KOWARI_DIR/../conf/kowari-config-2servers.xml \
            >> kowari2-output 2>> kowari2-output &
        cd $OLD_DIR
        echo "Started embedded KOWARI servers"
    ;;

    stop)
        # stop the rmiregistry and the server
        /sbin/start-stop-daemon --stop --oknodo --quiet --pidfile $KOWARI1PID
        sleep $SLEEP_TIME
        /sbin/start-stop-daemon --stop --oknodo --quiet --pidfile $KOWARI2PID
        sleep $SLEEP_TIME
        /sbin/start-stop-daemon --stop --oknodo --quiet --pidfile $RMIPID

        # clean up generated files
        if [ -f $RMIPID ] ; then
          /bin/rm $RMIPID
        fi
        if [ -f $KOWARI1PID ] ; then
          /bin/rm $KOWARI1PID
        fi
        if [ -f $KOWARI2PID ] ; then
          /bin/rm $KOWARI2PID
        fi

        echo "Stopped embedded Kowari servers"
    ;;

    restart)
        $0 stop
        sleep $SLEEP_TIME
        $0 start
    ;;

    *)
        echo "Starts/stops two embedded Kowari servers and the rmiregistry." >&2
        echo "Usage: $0 {start|stop|restart}" >&2
        exit 1
    ;;
esac

exit 0
