				<ul>
						<li><a href="/inferencing/inferintro.html">Introduction to Inferencing</a></li>
						<ul>
								<li><a href="/inferencing/infersitu.html">Current Situation</a></li>
								<ul class="toc">
										<li><a href="/inferencing/infersitu.html#o3015">First Search</a></li>
										<li><a href="/inferencing/infersitu.html#o3016">Second Search</a></li>
										<li><a href="/inferencing/infersitu.html#o3017">Third Search</a></li>
								</ul>
								<li><a href="/inferencing/infersemweb.html">Semantic Web</a></li>
								<ul class="toc">
										<li><a href="/inferencing/infersemweb.html#o2644">Elements of the Semantic Web</a></li>
										<ul>
												<li><a href="/inferencing/infersemweb.html#o2645">Classes</a></li>
												<li><a href="/inferencing/infersemweb.html#o2646">Properties</a></li>
												<li><a href="/inferencing/infersemweb.html#o3019">Ranges</a></li>
												<li><a href="/inferencing/infersemweb.html#o3018">Domains</a></li>
												<li><a href="/inferencing/infersemweb.html#o2647">Additional Features for Describing Classes and Properties</a></li>
										</ul>
										<li><a href="/inferencing/infersemweb.html#o2648">Implementing Inferencing</a></li>
								</ul>
								<li><a href="/inferencing/infersummary.html">Summary</a></li>
						</ul>
						<li><a href="/inferencing/infermulgara.html">Inferencing and Mulgara</a></li>
						<ul class="toc">
								<li><a href="/inferencing/infermulgara.html#o2726">Models Required</a></li>
								<ul>
										<li><a href="/inferencing/infermulgara.html#o2727">Base Model</a></li>
										<li><a href="/inferencing/infermulgara.html#o2728">Schema Model</a></li>
										<li><a href="/inferencing/infermulgara.html#o2729">Inference Model</a></li>
								</ul>
								<li><a href="/inferencing/infermulgara.html#o2730">An Example</a></li>
						</ul>
						<li><a href="/inferencing/owl.html">OWL-Lite Operations Using iTQL</a></li>
						<ul>
								<li><a href="/inferencing/entailment.html">Entailment</a></li>
								<ul class="toc">
										<li><a href="/inferencing/entailment.html#o2802">owl:AllDifferent</a></li>
										<li><a href="/inferencing/entailment.html#o2803">owl:distinctMembers</a></li>
										<li><a href="/inferencing/entailment.html#o2804">owl:Class</a></li>
										<li><a href="/inferencing/entailment.html#o2805">owl:FunctionalProperty</a></li>
										<li><a href="/inferencing/entailment.html#o2930">owl:sameAs</a></li>
										<ul>
												<li><a href="/inferencing/entailment.html#o2931">Transitivity</a></li>
												<li><a href="/inferencing/entailment.html#o2932">Reflexivity</a></li>
												<li><a href="/inferencing/entailment.html#o2933">Symmetry</a></li>
												<li><a href="/inferencing/entailment.html#o2934">Class Equivalence</a></li>
												<li><a href="/inferencing/entailment.html#o2935">Property Equivalence</a></li>
												<li><a href="/inferencing/entailment.html#o2936">Inconsistencies</a></li>
												<li><a href="/inferencing/entailment.html#o2937">Note on Consistency Checking and Inferences</a></li>
										</ul>
										<li><a href="/inferencing/entailment.html#o2807">owl:InverseFunctionalProperty</a></li>
										<li><a href="/inferencing/entailment.html#o2808">owl:differentFrom</a></li>
										<ul>
												<li><a href="/inferencing/entailment.html#o2945">Symmetry</a></li>
												<li><a href="/inferencing/entailment.html#o2946">Inconsistencies</a></li>
										</ul>
										<li><a href="/inferencing/entailment.html#o2809">owl:inverseOf</a></li>
										<li><a href="/inferencing/entailment.html#o2811">owl:SymmetricProperty</a></li>
										<li><a href="/inferencing/entailment.html#o2812">owl:TransitiveProperty</a></li>
										<li><a href="/inferencing/entailment.html#o2813">owl:equivalentClass</a></li>
										<li><a href="/inferencing/entailment.html#o2814">owl:equivalentProperty</a></li>
										<li><a href="/inferencing/entailment.html#o2815">owl:intersectionOf</a></li>
								</ul>
								<li><a href="/inferencing/consistency.html">Consistency Checking</a></li>
								<ul class="toc">
										<li><a href="/inferencing/consistency.html#o2817">Restricting Data Types</a></li>
										<ul>
												<li><a href="/inferencing/consistency.html#o2818">owl:allValuesFrom</a></li>
												<li><a href="/inferencing/consistency.html#o2819">owl:someValuesFrom</a></li>
										</ul>
										<li><a href="/inferencing/consistency.html#o2820">Cardinality Operations</a></li>
										<ul>
												<li><a href="/inferencing/consistency.html#o2821">owl:cardinality</a></li>
												<li><a href="/inferencing/consistency.html#o2822">owl:minimumCardinality</a></li>
												<li><a href="/inferencing/consistency.html#o2823">owl:maximumCardinality</a></li>
										</ul>
										<li><a href="/inferencing/consistency.html#o2824">owl:Nothing</a></li>
										<li><a href="/inferencing/consistency.html#o2825">owl:Restriction</a></li>
										<li><a href="/inferencing/consistency.html#o2826">owl:Thing</a></li>
								</ul>
						</ul>
						<li><a href="/inferencing/ontomanage.html">Ontology Management</a></li>
						<ul class="toc">
								<li><a href="/inferencing/ontomanage.html#o2828">owl:AnnotationProperty</a></li>
								<li><a href="/inferencing/ontomanage.html#o2829">owl:backwardCompatibleWith</a></li>
								<li><a href="/inferencing/ontomanage.html#o2830">owl:DeprecatedClass</a></li>
								<li><a href="/inferencing/ontomanage.html#o2831">owl:DeprecatedProperty</a></li>
								<li><a href="/inferencing/ontomanage.html#o2832">owl:imports</a></li>
								<li><a href="/inferencing/ontomanage.html#o2833">owl:incompatibleWith</a></li>		
								<li><a href="/inferencing/ontomanage.html#o2834">owl:Ontology</a></li>
								<li><a href="/inferencing/ontomanage.html#o2835">owl:OntologyProperty</a></li>		
								<li><a href="/inferencing/ontomanage.html#o2836">owl:priorVersion</a></li>		
								<li><a href="/inferencing/ontomanage.html#o2837">owl:versionInfo</a></li>		
						</ul>
						<li><a href="/inferencing/sofa.html">SOFA</a></li>
						<ul class="toc">
								<li><a href="/inferencing/sofa.html#o2624">Prerequisites</a></li>
								<li><a href="/inferencing/sofa.html#o2625">Getting Started</a></li>
								<li><a href="/inferencing/sofa.html#o2626">Creating the Ontology</a></li>
								<li><a href="/inferencing/sofa.html#o2627">Changing the Backing of an Ontology</a></li>
								<li><a href="/inferencing/sofa.html#o2628">Populating the Ontology</a></li>
								<li><a href="/inferencing/sofa.html#o2639">Compiling and Running the Example</a></li>
								<li><a href="/inferencing/sofa.html#o2629">Integration</a></li>
						</ul>
						<li><a href="/inferencing/inferexample.html">Inferencing Examples Using SOFA and iTQL</a></li>
						<ul class="toc">
								<li><a href="/inferencing/inferexample.html#o2734">iTQL Inferencing</a></li>
								<li><a href="/inferencing/inferexample.html#o2735">SOFA Inferencing</a></li>
								<li><a href="/inferencing/inferexample.html#o2736">Should I use SOFA or iTQL?</a></li>
						</ul>
				</ul>
