				<ul>
						<li><a href="/itqlcommands/alias.html">alias</a></li>
						<li><a href="/itqlcommands/backup.html">backup</a></li>
						<li><a href="/itqlcommands/comment.html">comment (#)</a></li>
						<li><a href="/itqlcommands/commit.html">commit</a></li>
						<li><a href="/itqlcommands/create.html">create</a></li>
						<li><a href="/itqlcommands/delete.html">delete</a></li>	
						<li><a href="/itqlcommands/drop.html">drop</a></li>	
						<li><a href="/itqlcommands/execute.html">execute</a></li>	
						<li><a href="/itqlcommands/help.html">help</a></li>	
						<li><a href="/itqlcommands/insert.html">insert</a></li>	
						<li><a href="/itqlcommands/load.html">load</a></li>	
						<li><a href="/itqlcommands/quit.html">quit</a></li>	
						<li><a href="/itqlcommands/restore.html">restore</a></li>	
						<li><a href="/itqlcommands/rollback.html">rollback</a></li>	
						<li><a href="/itqlcommands/select.html">select</a></li>
						<ul class="toc">
								<li><a href="/itqlcommands/select.html#o188">select Clause</a></li>
								<li><a href="/itqlcommands/select.html#o189">from Clause</a></li>
								<li><a href="/itqlcommands/select.html#o197">where Clause</a></li>
								<ul class="toc">
										<li><a href="/itqlcommands/select.html#o1530">in Specifier</a></li>
										<li><a href="/itqlcommands/select.html#o1531">Assigning a Value to a Variable (mulgara:is)</a></li>
										<li><a href="/itqlcommands/select.html#o1532">Traversing a Graph (walk Function)</a></li>
										<li><a href="/itqlcommands/select.html#o1535">Transitive Closure (trans Function)</a></li>
										<li><a href="/itqlcommands/select.html#o2768">exclude Function</a></li>
										<ul class="toc">
												<li><a href="/itqlcommands/select.html#o2769">Standard Queries</a></li>
												<li><a href="/itqlcommands/select.html#o2770">exclude($s $p $o)</a></li>
												<li><a href="/itqlcommands/select.html#o2771">Subqueries</a></li>
										</ul>
								</ul>
								<li><a href="/itqlcommands/select.html#o190">order by Clause</a></li>
								<li><a href="/itqlcommands/select.html#o191">limit Clause</a></li>
								<li><a href="/itqlcommands/select.html#o192">offset Clause</a></li>
								<li><a href="/itqlcommands/select.html#o193">subquery Function</a></li>
								<li><a href="/itqlcommands/select.html#o194">count Function</a></li>
								<li><a href="/itqlcommands/select.html#o2776">having Clause</a></li>
						</ul>
						<li><a href="/itqlcommands/set.html">set</a></li>
				</ul>
