				<ul>
						<li><a href="/resolvers/resolverdbclass.html">Resolver Database Class</a></li>
						<ul class="toc">
								<li><a href="/resolvers/resolverdbclass.html#o2554">Node Pools</a></li>
								<li><a href="/resolvers/resolverdbclass.html#o2555">String Pools</a></li>
								<li><a href="/resolvers/resolverdbclass.html#o2556">Temporary Pools</a></li>
								<li><a href="/resolvers/resolverdbclass.html#o2557">Persistent Pools</a></li>
								<li><a href="/resolvers/resolverdbclass.html#o2558">System Resolver Factory</a></li>
						</ul>
						<li><a href="/resolvers/resolverdbclass.html#o2559">Internal Resolvers</a></li>
						<li><a href="/resolvers/resolverdbclass.html#o2560">External Resolvers</a></li>
				</ul>
